### PR TITLE
Add package.json and publish script

### PR DESCRIPTION
**Pull request by tylerthebuildor**
K so I added a publish script to make it dead easy to update on NPM. You'll need to create an NPM account then run `npm login` in your local terminal if you haven't already done that.

I've never actually tried it yet but the `publish.sh` script I committed should make it really easy to update the package whenever you want. Just run: `./publish.sh` from the terminal in the project directory and then type "patch", "minor", or "major" then enter. And you'll have to confirm with "yes" then enter.

Just do a "patch" this time around but if you haven't already looked it up you should review http://semver.org/ to know which option to choose in the future.

### CODE REVIEW

**Comment by lawrentiy** [comment]
OK. I can publish it a little later

**Comment by tylerthebuildor** [comment]
Sounds good, I can work on the other TODO item later as well.

**Comment by lawrentiy** [comment]
Really, in one of projects I`ve done the second TODO. but I can`t found now in which one!

**Comment by tylerthebuildor** [comment]
No worries, I can check it out later. Your component is very clean and elegant compared to all the other ones I found. I like it much better. I'd love to help you make it even more awesome so everyone uses it.

**Review by lawrentiy — APPROVED** [review]

**Pull request merged**
